### ISSUE TITLE
Adjusting brightness in context menu for light in OFF state does not update state to ON

### ISSUE THREAD

**Issue by lucymhdavies** [tatey/Lighting#12]
![context](https://cloud.githubusercontent.com/assets/1116529/9567609/3c8d4748-4f2a-11e5-8669-ab97aa6b03ef.gif)

Steps to Reproduce:
1) Have a light in the OFF state
2) Open the Context Menu
3) Adjust the Brightness of the light

Expected:
LIFX bulb switches on at the set brightness.
Icon in notification center enters the ON state.

Actual:
LIFX bulb switches on at the set brightness (no issue here).
Icon in notification center remains in the OFF state.

**Comment by tatey** [comment]
Thanks for reporting. I'll take a look when I get some free time.

**Comment by tatey** [comment]
Hi @lucymhdavies. This should be fixed in [1.1.1](https://github.com/tatey/Lighting/releases/tag/1.1.1). Thanks for reporting!

**Comment by lucymhdavies** [comment]
Looks good. Thanks :)
