### ISSUE TITLE
An Icon

### ISSUE THREAD

**Issue by TheDaem0n** [tatey/Lighting#16]
Hey dudes,

if I make a solid icon file, would some of you lovely devs push that icon into the app? I feel really awkward with that default "no-icon" icon.

**Comment by TheDaem0n** [comment]
Thoughts?

![bulb oval](https://cloud.githubusercontent.com/assets/15079453/10428845/2fadca14-70ec-11e5-9c55-8c02563c8928.png)

**Comment by TheDaem0n** [comment]
Here it is in the dock with Apple icons.

![screen shot 2015-10-12 at 14 19 47](https://cloud.githubusercontent.com/assets/15079453/10428862/4cd64fbc-70ec-11e5-845b-8f31888b5f12.png)

**Comment by tatey** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 

That's a brilliant icon and we'd love to have it for Lighting. I'm honestly really stoked.

Are you comfortable with submitting a pull request to get it into the project?

Again, thanks so much.

**Comment by TheDaem0n** [comment]
Let me try.

=)


–
G.
UX

**Comment by tatey** [comment]
I've just added it to the Image.xcassets file. This format has superseded .icons on OS X, although .icns is still compatible. Like .icns it lets you provide an icon file for retina and non-retina at different sizes. I've just used the PNG you provided.

![screen shot 2015-10-13 at 6 23 02 pm](https://cloud.githubusercontent.com/assets/19860/10450394/5eb12698-71dd-11e5-8b93-0969ca9d5f37.png)

Dock:

![screen shot 2015-10-13 at 6 21 55 pm](https://cloud.githubusercontent.com/assets/19860/10450399/63a0fb06-71dd-11e5-896b-1d1907305465.png)

Notification Center:

![screen shot 2015-10-13 at 6 21 39 pm](https://cloud.githubusercontent.com/assets/19860/10450407/6fe4d6f8-71dd-11e5-8890-1aadcddb2345.png)

I've also added it to the README of the project too. It's just so pretty :smile:

**Comment by tatey** [comment]
@TheDaem0n I've just published [1.1.5](https://github.com/tatey/Lighting/releases/tag/1.1.5) with your new App Icon. Give it a shot and let me know how you go. We can continue tweaking if you feel the need. It's very easy to do a release. Your contribution is greatly appreciated.

**Comment by TheDaem0n** [comment]
Hey,

not sure if you did this already, looking at the screens you have sent, but we could for the small sizes remove the outer white border.

See attached.

So perhaps 16pt ones, even @2x, could be this one, as the white border does not even show at those sizes, just makes things messier.

And other sizes look sweet! 





--
Goran Peuc, on the move

On 12 Oct, 2015,at 10:06 PM, Tate Johnson <notifications@github.com> wrote:

I've just added it to the Image.xcassets file. This format has superseded .icons on OS X, although .icns is still compatible. Like .icns it lets you provide an icon file for retina and non-retina at different sizes. I've just used the PNG you provided.

Dock:

Notification Center:

I've also added it to the README of the project too. It's just so pretty

**Comment by TheDaem0n** [comment]
Yeah, I think this would look better if for those super small sizes we removed the white border.




--
Goran Peuc, on the move

On 12 Oct, 2015,at 10:06 PM, Tate Johnson <notifications@github.com> wrote:

I've just added it to the Image.xcassets file. This format has superseded .icons on OS X, although .icns is still compatible. Like .icns it lets you provide an icon file for retina and non-retina at different sizes. I've just used the PNG you provided.

Dock:

Notification Center:

I've also added it to the README of the project too. It's just so pretty

**Comment by tatey** [comment]
32pt on 1x Mac

![screen shot 2015-10-13 at 9 05 18 pm](https://cloud.githubusercontent.com/assets/19860/10453287/459b3386-71ee-11e5-8bb3-8756818016c9.png)

16pt 1x Mac
![screen shot 2015-10-13 at 9 05 43 pm](https://cloud.githubusercontent.com/assets/19860/10453289/4e802f56-71ee-11e5-9e19-5f624a792a3f.png)

And here's all of them.

![screen shot 2015-10-13 at 9 06 56 pm](https://cloud.githubusercontent.com/assets/19860/10453292/5b218138-71ee-11e5-85ec-b8c4993019a6.png)

I did experiment with removing the border from 32pt on 1x but it looks better with it.

**Comment by TheDaem0n** [comment]
Roger, then we are good as it is in 1.1.5!


On 13 Oct, 2015,at 12:07 AM, Tate Johnson <notifications@github.com> wrote:

32pt on 1x Mac

16pt 1x Mac

And here's all of them.

I did experiment with removing the border from 32pt on 1x but it looks better with it.

**Comment by tatey** [comment]
Cool.

I also updated the Sketch file with the slice sizes.

Considering this issue closed :+1:
