### ISSUE TITLE
Doesn't show up in macOS 10.12

### ISSUE THREAD

**Issue by O-Dog5960** [tatey/Lighting#19]

**Comment by nzeppos** [comment]
Likewise. No widget appears in the notification centre and since most people nowadays use 10.12, this bug renders this application useless. Uninstalling.

**Comment by lucymhdavies** [comment]
Works fine for me in 10.12

**Comment by nzeppos** [comment]
Nice, there may be hope still, I'll do some more research and find out more.

**Comment by tatey** [comment]
Like @lucymhdavies I can confirm this is working for me in 10.12. Try the new [1.1.6 release](https://github.com/tatey/Lighting/releases/tag/1.1.6).

![screen shot 2017-07-08 at 7 41 54 pm](https://user-images.githubusercontent.com/19860/27984323-1d947f6a-6417-11e7-9d25-3c0b9aa0d35b.png)
