### ISSUE TITLE
Invalid access token

### ISSUE THREAD

**Issue by pehuensolari** [tatey/Lighting#20]
Im always receiving "invalid access token" when copying my access token from lifx cloud Account....

I have generated more than 4 access token but anyone worked. (MacOS Sierra)

**Comment by tatey** [comment]
What happens if you paste your token in "Try it Out" at https://api.developer.lifx.com/docs/list-lights?

**Comment by pehuensolari** [comment]
It worked! I have tried it and I received a "200 OK" response status.

**Comment by tatey** [comment]
Okay, and that same token doesn’t work when you paste it into Lightning?

**Comment by pehuensolari** [comment]
Exactly... I tried the same token in the lightning app and It didn't work :/

Lucas Pehuen Solari

**Comment by kretash** [comment]
Did any solution come up? I'm running into the same issue.

**Comment by pehuensolari** [comment]
Nothing yet :/

Lucas Pehuen Solari

**Comment by frakman1** [comment]
I have the same problem  @tatey 
I am using your latest code on Sierra 10.12.5. My tokens work on life.space and via curl, but are declared invalid when used in the  Lighting app. Any idea what went wrong?

**Comment by Bluebie** [comment]
I'm having this issue, installed via brew, I've tried with a freshly generated token, and a token generated about 6 months ago. Both come back invalid. macOS 10.12.5. macOS Console log starting from clicking Login until error results:

```
default	23:01:45.281376 +1000	Lighting	UNIX error exception: 17
default	23:01:45.281495 +1000	Lighting	0x608000274280 opened /private/var/db/mds/system/mdsDirectory.db: 50744 bytes
default	23:01:45.283190 +1000	Lighting	UNIX error exception: 17
default	23:01:45.283396 +1000	Lighting	0x60000046fe00 opened /Users/user/Library/Keychains/login.keychain-db: 1164544 bytes
default	23:01:45.290503 +1000	Lighting	0x6000004620c0 opened /Library/Keychains/System.keychain: 177900 bytes
default	23:01:45.296352 +1000	Lighting	TIC TCP Conn Start [9:0x608000188bc0]
default	23:01:45.557116 +1000	Lighting	TIC TCP Conn Event [9:0x608000188bc0]: 1 Err(0)
default	23:01:45.557149 +1000	Lighting	TIC TCP Conn Connected [9:0x608000188bc0]: Err(0)
default	23:01:45.557318 +1000	Lighting	TIC Enabling TLS [9:0x608000188bc0]
default	23:01:45.821713 +1000	Lighting	TIC TLS Event [9:0x608000188bc0]: 2, Pending(0)
default	23:01:45.832681 +1000	Lighting	TIC TLS Event [9:0x608000188bc0]: 11, Pending(0)
default	23:01:45.833580 +1000	Lighting	TIC TLS Event [9:0x608000188bc0]: 12, Pending(0)
default	23:01:45.833670 +1000	Lighting	TIC TLS Event [9:0x608000188bc0]: 14, Pending(0)
default	23:01:45.837924 +1000	Lighting	TIC TLS Trust Result [9:0x608000188bc0]: 0
default	23:01:46.213471 +1000	Lighting	TIC TLS Event [9:0x608000188bc0]: 20, Pending(0)
default	23:01:46.215492 +1000	Lighting	TIC TCP Conn Event [9:0x608000188bc0]: 8 Err(0)
default	23:01:46.215654 +1000	Lighting	TIC TLS Handshake Complete [9:0x608000188bc0]
default	23:01:46.222231 +1000	Lighting	TIC TCP Conn Start [10:0x60000018f560]
default	23:01:46.460726 +1000	Lighting	TIC TCP Conn Event [10:0x60000018f560]: 1 Err(0)
default	23:01:46.460767 +1000	Lighting	TIC TCP Conn Connected [10:0x60000018f560]: Err(0)
default	23:01:46.461052 +1000	Lighting	TIC Enabling TLS [10:0x60000018f560]
default	23:01:46.706744 +1000	Lighting	TIC TLS Event [10:0x60000018f560]: 2, Pending(0)
default	23:01:46.710075 +1000	Lighting	TIC TLS Event [10:0x60000018f560]: 11, Pending(0)
default	23:01:46.710924 +1000	Lighting	TIC TLS Event [10:0x60000018f560]: 12, Pending(0)
default	23:01:46.710987 +1000	Lighting	TIC TLS Event [10:0x60000018f560]: 14, Pending(0)
default	23:01:46.717660 +1000	Lighting	TIC TLS Trust Result [10:0x60000018f560]: 0
default	23:01:46.928438 +1000	Lighting	TIC TLS Event [10:0x60000018f560]: 20, Pending(0)
default	23:01:46.929561 +1000	Lighting	TIC TCP Conn Event [10:0x60000018f560]: 8 Err(0)
default	23:01:46.929692 +1000	Lighting	TIC TLS Handshake Complete [10:0x60000018f560]
default	23:01:47.185196 +1000	Lighting	TIC TCP Conn Cancel [7:0x608000383670]
default	23:01:47.185345 +1000	Lighting	TIC TCP Conn Cancel [8:0x608000382ff0]
```

Lighting didn't generate any output to stdout. UNIX Error 17 incidentally is EEXISTS, indicating "file exists".

**Comment by tatey** [comment]
Thanks for posting that log Jenna.

I haven’t had any time to look at this yet, but I suspect it might be something to do with how the token is being written to the keychain. I’m pretty sure you get the unauthorized error if an empty/blank token is read back. That would also explain why the token works on the HTTP API documentation, but not in the widget.

**Comment by Esya** [comment]
Same here, getting an invalid token message with a valid token.

**Comment by segan5** [comment]
I managed to fix this error and submitted a PR for it. My branch works on macOS Sierra 10.12.5

**Comment by tatey** [comment]
Hey everyone. I've just merged @segan5's [pull request](https://github.com/tatey/Lighting/pull/21) and cut a new release which fixes the bug. Get it from https://github.com/tatey/Lighting/releases/tag/1.1.6.

Huge shout out to @segan5 for fixing this! 👏 🎉

**Comment by frakman1** [comment]
I just tried it and it now works again on my MacBook Air Sierra (OS X 10.12.5)
Thanks guys!

**Comment by pehuensolari** [comment]
Thanks guys!! It’s working 😀
