### ISSUE TITLE
New styling and colour scheme for 10.12.

### ISSUE THREAD

**Issue by tatey** [tatey/Lighting#22]
The widget was originally built on 10.10. The whole notification center got a significant revamp in 10.12. The widget still works, but it doesn't look as good as it could.

I'd be happy to drop support for < 10.12 to make it easier to maintain going forward. My suggestions:

* Use light colour scheme
* Fix cell alignment
* Update screenshots in README.

![screen shot 2017-07-08 at 7 41 54 pm](https://user-images.githubusercontent.com/19860/27984335-67fdbf6c-6417-11e7-9fca-265cda1a0ea6.png)

**Comment by segan5** [comment]
Agree with all your suggestions. 

Submitted a PR for the light colour scheme, its just a field you need to add in the info.plist as per https://stackoverflow.com/questions/39811118/sierra-notification-center-widgets-background-colour

I also expanded white values you can set in the widget to be in line with the iOS app. Feel free to reject this if you don't think its appropriate.

**Comment by tatey** [comment]
Thanks again for your contribution in #23. As agreed I'm splitting out the alignment into a [new issue](https://github.com/tatey/Lighting/issues/24).
