### ISSUE TITLE
Nice alignment of cells in 10.12

### ISSUE THREAD

**Issue by tatey** [tatey/Lighting#24]
Continuing from #23 we want to nicely align the cells in 10.12 to make it look like a really polished widget.

* The spacing on the left looks too close to the border.
* Consider adding a couple of stock widgets and pick something that makes it feel like something Apple would have picked. See battery in second screenshot with old style.

Happy to drop support for < 10.12 if it breaks alignment in those versions to keep maintenance simpler.

![27984717-2b1108a8-6420-11e7-9a98-25152c849cae](https://user-images.githubusercontent.com/19860/27989660-f06ed322-6480-11e7-93b4-c3640e010114.png)

![27984335-67fdbf6c-6417-11e7-9fca-265cda1a0ea6](https://user-images.githubusercontent.com/19860/27989670-21ba2fda-6481-11e7-9393-c90051a773af.png)

**Comment by segan5** [comment]
Submitted #25 to fix the cell alignment. 

@tatey I don't have as many lights as you do, can you test it out? Unfortunately I can't do much about the look of the widgets because I don't have any design chops 😛

**Comment by tatey** [comment]
Looks really good! Nice one.

![screen shot 2017-07-13 at 9 20 55 pm](https://user-images.githubusercontent.com/19860/28164141-485f762a-6811-11e7-963d-b2c495ec511c.png)

**Comment by tatey** [comment]
Have merged #25 into master. I'll find some time to tweak the colours for the light style and then cut a new release.

You're a champ @segan5!

**Comment by tatey** [comment]
Hey @segan5. Just letting you know I've cut a new release https://github.com/tatey/Lighting/releases/tag/1.1.7. I've also updated screenshots in the README.

**Comment by segan5** [comment]
@tatey thanks for the heads up. Also noticed the other day there is a minor grammatical error in your project's description.

"Control LIFX lights from you're Mac via a Notification Center Widget" should be "Control LIFX lights from **your** Mac via a Notification Center Widget"

**Comment by tatey** [comment]
Ahhh. Good pickup. I’ve fixed this up.
