### ISSUE TITLE
Buildtime error Lighting.xcodeproj on xcode 10.1 using Mojave 10.14.6 

### ISSUE THREAD

**Issue by rohitmitt** [tatey/Lighting#32]
Swift 3.0 or below doesn't work with Mojave. I installed xcode 10.1 to allow conversion from 3.0 to 4.2, but it is coming up with syntax errors. 

Can someone help explain the LIFXHTTPKit module and how I install it? I am extremely new to programming and xcode especially, so it would be nice to try and understand this. 
<img width="272" alt="Screen Shot 2021-11-09 at 7 04 19 PM" src="https://user-images.githubusercontent.com/51212933/141025209-cf7f8428-e6a1-4f26-a27f-287fc8948731.png">
g

**Comment by rohitmit98** [comment]
Never mind. I updated to Monterey OS! There isn't a widget app available neither for LIFx or HomeKit but could be a useful tool to have.
